# Generated by Django 4.2.5 on 2023-10-03 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
        ('groups', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='x', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='trait',
            field=models.ManyToManyField(related_name='y', to='traits.trait'),
        ),
    ]
