# Generated by Django 4.2.5 on 2023-10-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
        ('groups', '0001_initial'),
        ('pets', '0002_alter_pet_group_alter_pet_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='trait',
            field=models.ManyToManyField(to='traits.trait'),
        ),
    ]
