# Generated by Django 4.2.5 on 2023-10-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_group_alter_pet_trait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='trait',
            new_name='traits',
        ),
    ]
