# Generated by Django 4.2.5 on 2023-10-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('pets', '0004_rename_trait_pet_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Not Informed', 'Default'), ('Male', 'Male'), ('Female', 'Female')], default=('Not Informed', 'Default'), max_length=20),
        ),
    ]
