# Generated by Django 4.2.5 on 2023-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_group_alter_pet_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Not Informed', 'Not Informed'), ('Male', 'Male'), ('Female', 'Female')], default='Not Informed', max_length=20),
        ),
    ]
