# Generated by Django 4.2.5 on 2023-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_rename_created_atc_trait_created_at'),
        ('pets', '0008_alter_pet_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='pets', to='traits.trait'),
        ),
    ]
