# Generated by Django 4.2.5 on 2023-10-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_trait_created_atc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='created_atc',
            new_name='created_at',
        ),
    ]
